---
title: "Data Science Capstone: Final project submission"
author: "G S Lopes"
date: "11/6/2020"
output: slidy_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## App: The Crystal Ball

Hi! Welcome to this very simple App called "The Crystal Ball".

The Crystal Ball uses Natural Language Processing (NLP) techniques to predict the next word of a sentence.

## Data: Twitter, Blogs, and News

The prediction model used in The Crystal Ball uses text from Twitter, Blogs, and News.

This way, the model can accurately predict the next word of sentences written in different contexts.

## Prediction model: Bi-, Tri-, Quad- grams

N-grams are defined as "a contiguous sequence of n items from a given sample of text or speech." (Wikipedia)

The Crystal Ball uses Bi-, Tri-, and Quad- grams in an attempt to make the best prediction for you.

## Instructions: The Crystal Ball

Now, go to The Crystal Ball and enjoy!

Type a short sentence and see what The Crystal Ball predicts.

For example, try typing "How are", and you will see "How are you".

## Conclusion

For more details, please visit [GitHub repo](https://github.com/guislopes/Coursera_Capstone)

I hope you enjoy!

Thank you!

